lint:
  files_unchanged:
    - .gitignore
nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: "@kbestak, @FloWuenne"
  description: An analysis pipeline for Molecular Cartography data from Resolve Biosciences.
  force: false
  is_nfcore: true
  name: molkart
  org: nf-core
  outdir: .
  version: 1.1.0
